// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJOKdOElpBMYjVgX9yLl1HLc9kc0r5hoM',
    appId: '1:70499913861:web:6bc31541a50e08614399ec',
    messagingSenderId: '70499913861',
    projectId: 'essencia-et-co',
    authDomain: 'essencia-et-co.firebaseapp.com',
    storageBucket: 'essencia-et-co.firebasestorage.app',
    measurementId: 'G-NVNV3QBLM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtXy-chh0lEFp_puZNqiIk93xpJLEyQ6g',
    appId: '1:70499913861:android:5d8ec338cf8d73534399ec',
    messagingSenderId: '70499913861',
    projectId: 'essencia-et-co',
    storageBucket: 'essencia-et-co.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9jGDlXWzHyNIXdGhCp0tRLJxCjUJ0B1Q',
    appId: '1:70499913861:ios:f1a902b0e0e8b6514399ec',
    messagingSenderId: '70499913861',
    projectId: 'essencia-et-co',
    storageBucket: 'essencia-et-co.firebasestorage.app',
    iosBundleId: 'com.essenciaco.essenciaCo',
  );
}
